return {
  prettier = {
    ".prettierrc",
    ".prettierrc.cjs",
    ".prettierrc.cts",
    ".prettierrc.js",
    ".prettierrc.json",
    ".prettierrc.json5",
    ".prettierrc.mjs",
    ".prettierrc.mts",
    ".prettierrc.toml",
    ".prettierrc.ts",
    ".prettierrc.yaml",
    ".prettierrc.yml",
  },

  eslint = {
    ".eslintrc",
    ".eslintrc.cjs",
    ".eslintrc.js",
    ".eslintrc.json",
    ".eslintrc.yaml",
    ".eslintrc.yml",
    "eslint.config.cjs",
    "eslint.config.cts",
    "eslint.config.js",
    "eslint.config.mjs",
    "eslint.config.mts",
    "eslint.config.ts",
  },

  babel = {
    ".babelrc",
    ".babelrc.cjs",
    ".babelrc.js",
    ".babelrc.json",
    ".babelrc.mjs",
    ".babelrc.mts",
    "babel.config.cjs",
    "babel.config.cts",
    "babel.config.js",
    "babel.config.mjs",
    "babel.config.mts",
    "babel.config.ts",
  },

  vite = {
    "vite.config.cjs",
    "vite.config.cts",
    "vite.config.js",
    "vite.config.mjs",
    "vite.config.mts",
    "vite.config.ts",
  },

  vitest = {
    "vitest.config.cjs",
    "vitest.config.cts",
    "vitest.config.js",
    "vitest.config.mjs",
    "vitest.config.mts",
    "vitest.config.ts",
    "vitest.workspace.cjs",
    "vitest.workspace.cts",
    "vitest.workspace.js",
    "vitest.workspace.mjs",
    "vitest.workspace.mts",
    "vitest.workspace.ts",
  },

  jest = {
    "jest.config.cjs",
    "jest.config.cts",
    "jest.config.js",
    "jest.config.json",
    "jest.config.mjs",
    "jest.config.mts",
    "jest.config.ts",
  },

  docker = {
    ".dockerignore",
    "docker-compose.yaml",
    "docker-compose.yml",
    "Dockerfile",
    "Dockerfile.dev",
    "Dockerfile.prod",
  },

  dotenv = {
    ".env.example",
    ".env.local",
    ".env.production",
    ".env.prod",
    ".env.staging",
    ".env.test",
  },

  webpack = {
    "webpack.config.cjs",
    "webpack.config.cts",
    "webpack.config.js",
    "webpack.config.mjs",
    "webpack.config.mts",
    "webpack.config.ts",
  },

  tsconfig = {
    "tsconfig.json",
    "tsconfig.app.json",
    "tsconfig.base.json",
    "tsconfig.build.json",
    "tsconfig.node.json",
  },
}
